name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

jobs:
  doc:
    name: Doc
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - run: cargo doc --no-deps

  lint:
    name: Rustfmt and clippy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable

      - name: Rustfmt
        run: cargo fmt --all -- --check

      - name: Clippy
        run: cargo clippy --all-targets --all-features -- -D clippy::all

  build-default-feature:
    name: Build with default feature
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable

      - name: Install libusb
        run: |
          if [[ ${{ matrix.os }} == "ubuntu-latest" ]]; then
            sudo apt install pkg-config libusb-1.0-0-dev
          elif [[ ${{ matrix.os }} == "macos-latest" ]]; then
            brew install pkg-config libusb
          elif [[ ${{ matrix.os }} == "windows-latest" ]]; then
            git clone https://github.com/microsoft/vcpkg.git --depth 1
            vcpkg/bootstrap-vcpkg.bat
            vcpkg/vcpkg integrate install
            vcpkg/vcpkg install libusb
          fi

      - name: Build cameleon-gui
        run: |
          cargo build
  
  build-cv-feature:
    name: Build with default feature
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable

      - name: Install libusb
        run: |
          if [[ ${{ matrix.os }} == "ubuntu-latest" ]]; then
            sudo apt install pkg-config libusb-1.0-0-dev
          elif [[ ${{ matrix.os }} == "macos-latest" ]]; then
            brew install pkg-config libusb
          elif [[ ${{ matrix.os }} == "windows-latest" ]]; then
            git clone https://github.com/microsoft/vcpkg.git --depth 1
            vcpkg/bootstrap-vcpkg.bat
            vcpkg/vcpkg integrate install
            vcpkg/vcpkg install libusb
          fi

      - name: Build cameleon-gui
        run: |
          cargo build --features cv
